#  _____                               ____             _                     _  __ ____
# |_   _|__ _  _ __  ____ __ _ __  __ / ___|_   _  ___ | |_  ___   _ __ ___  | |/ /| __ )
#   | | / _` || '__||_  // _` |\ \/ /| |   | | | |/ __|| __|/ _ \ | '_ ` _ \ | ' / |  _ \
#   | || (_| || |    / /| (_| | >  < | |___| |_| |\__ \| |_| (_) || | | | | || . \ | |_) |
#   |_| \__,_||_|   /___|\__,_|/_/\_\ \____|\__,_||___/ \__|\___/ |_| |_| |_||_|\_\|____/
#

# TarzaxKB config
# v1.0.0

# Set kb
KB: 0.350
# Set attack cooldown
AttackCooldown: 9.0